// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import "@mantine/notifications/styles.css";
import "./globals.css";

import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import type { Metadata } from "next";
import { theme } from '@/theme';
import { ApolloWrapper } from '@/lib/apollo-wrapper';
import { Notifications } from "@mantine/notifications";
import { GlobalContextProvider } from './Context/store';

export const metadata: Metadata = {
  title: "GreenShop Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Notifications />
          <ApolloWrapper>
            <GlobalContextProvider>{children}</GlobalContextProvider>
          </ApolloWrapper>
        </MantineProvider>
      </body>
    </html>
  );
}
